---

- name: Set default PaperSize to A4
  command: paperconfig -p a4
  when: paperconf.stdout != "a4"

- name: Restart Cups
  service:
    name: cups
    state: reloaded
  when: cups_config.changed

